### ISSUE TITLE
Up the coverage on coveralls

### ISSUE THREAD

**Issue by beseven** [nhsuk/nearby-services-api#41]
Based on https://coveralls.io/builds/10036613 we have not been testing the non-happy path/error callbacks as thoroughly
Suggestions:
- use sinon-choi for mocking (https://www.npmjs.com/package/sinon-chai)
- raise errors - http://stackoverflow.com/questions/33998896/how-to-test-error-callback-in-node-js
- improve coverage

**Comment by st3v3nhunt** [comment]
Coverage includes all files and is running at 94% on the latest build https://coveralls.io/builds/14210187
Closing issue.
