### ISSUE TITLE
Stash un-staged files before test run and remove post-rewrite git hook

### ISSUE THREAD

**Issue by neilbmclaughlin** [nhsuk/nearby-services-api#5]
See [here](https://github.com/nhsuk/moment-opening-times/pull/41) for rational and changes required.

**Comment by st3v3nhunt** [comment]
I've tried to implement this and it causes problems when attempting to amend the last commit message via `git commit --amend`. Until that is sorted the issue isn't going to be worked on again.

**Comment by st3v3nhunt** [comment]
Closing due to it not working and an alternative approach to git hooks being needed with container based development environments
